# Extração de dados
## Carregamento do arquivo com a base de dados

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./ocorrencia.csv', sep=';', parse_dates=['ocorrencia_dia'], dayfirst=True)
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,80898,80898,80898,80898,80898,INCIDENTE GRAVE,-23.330278,-51.136667,LONDRINA,PR,...,2022-08-04,21:10:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
1,80895,80895,80895,80895,80895,INCIDENTE GRAVE,-16.70611111111,-43.82194444444,MONTES CLAROS,MG,...,2022-08-02,15:05:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2,80894,80894,80894,80894,80894,INCIDENTE,-15.438611,-51.598333,JUSSARA,GO,...,2022-07-31,13:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3,80887,80887,80887,80887,80887,INCIDENTE,-22.810000,-43.250556,RIO DE JANEIRO,RJ,...,2022-07-30,01:23:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,80886,80886,80886,80886,80886,INCIDENTE,-7.27888,-64.76944,LÁBREA,AM,...,2022-07-29,17:12:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [4]:
df.dtypes

codigo_ocorrencia                          int64
codigo_ocorrencia1                         int64
codigo_ocorrencia2                         int64
codigo_ocorrencia3                         int64
codigo_ocorrencia4                         int64
ocorrencia_classificacao                  object
ocorrencia_latitude                       object
ocorrencia_longitude                      object
ocorrencia_cidade                         object
ocorrencia_uf                             object
ocorrencia_pais                           object
ocorrencia_aerodromo                      object
ocorrencia_dia                    datetime64[ns]
ocorrencia_hora                           object
investigacao_aeronave_liberada            object
investigacao_status                       object
divulgacao_relatorio_numero               object
divulgacao_relatorio_publicado            object
divulgacao_dia_publicacao                 object
total_recomendacoes                        int64
total_aeronaves_envolvidas                 int64
ocorrencia_saida_pista                    object
dtype: object

In [5]:
df['ocorrencia_dia'].dt.day

0        4
1        2
2       31
3       30
4       29
        ..
5524     6
5525     6
5526     6
5527     6
5528     5
Name: ocorrencia_dia, Length: 5529, dtype: int64

## Validação da extração

In [7]:
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,80898,80898,80898,80898,80898,INCIDENTE GRAVE,-23.330278,-51.136667,LONDRINA,PR,...,2022-08-04,21:10:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
1,80895,80895,80895,80895,80895,INCIDENTE GRAVE,-16.70611111111,-43.82194444444,MONTES CLAROS,MG,...,2022-08-02,15:05:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2,80894,80894,80894,80894,80894,INCIDENTE,-15.438611,-51.598333,JUSSARA,GO,...,2022-07-31,13:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3,80887,80887,80887,80887,80887,INCIDENTE,-22.810000,-43.250556,RIO DE JANEIRO,RJ,...,2022-07-30,01:23:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,80886,80886,80886,80886,80886,INCIDENTE,-7.27888,-64.76944,LÁBREA,AM,...,2022-07-29,17:12:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5,80891,80891,80891,80891,80891,INCIDENTE,-23.626111,-46.656389,SÃO PAULO,SP,...,2022-07-29,20:50:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6,80896,80896,80896,80896,80896,INCIDENTE,-23.006944,-47.134444,CAMPINAS,SP,...,2022-07-29,23:40:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
7,80882,80882,80882,80882,80882,INCIDENTE,-22.3436,-49.0538,BAURU,SP,...,2022-07-27,17:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,2,NÃO
8,80883,80883,80883,80883,80883,INCIDENTE,-1.384722,-48.478889,BELÉM,PA,...,2022-07-27,19:18:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
9,80884,80884,80884,80884,80884,INCIDENTE,-0.05117,-51.07072,MACAPÁ,AP,...,2022-07-27,18:20:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

Importação de biblioteca  `pandera` para tratamento de dados do tipo datetime

In [9]:
import pandera as pa

Validar o tipo de dado. Caso haja uma data inconsistente, ocorrerá um erro, diferente da execução anterior, em que para uma data inconsitente o parse não funciona.

In [56]:
schema = pa.DataFrameSchema(
    columns={
        "codigo_ocorrencia":pa.Column(pa.Int),
        "codigo_ocorrencia1":pa.Column(pa.Int),
        "codigo_ocorrencia2":pa.Column(pa.Int),
        "codigo_ocorrencia3":pa.Column(pa.Int),
        "codigo_ocorrencia4":pa.Column(pa.Int),
        "ocorrencia_classificacao":pa.Column(pa.String),
        "ocorrencia_latitude":pa.Column(pa.String, nullable=True),
        "ocorrencia_longitude":pa.Column(pa.String, nullable=True),
        "ocorrencia_cidade":pa.Column(pa.String),
        "ocorrencia_uf":pa.Column(pa.String, pa.Check.str_length(2,3)),
        "ocorrencia_pais":pa.Column(pa.String),
        "ocorrencia_aerodromo":pa.Column(pa.String),
        "ocorrencia_dia":pa.Column(pa.DateTime),
        "ocorrencia_hora":pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        "investigacao_aeronave_liberada":pa.Column(pa.String, nullable=True),
        "investigacao_status":pa.Column(pa.String, nullable=True),
        "divulgacao_relatorio_numero":pa.Column(pa.String, nullable=True),
        "divulgacao_relatorio_publicado":pa.Column(pa.String),
        "divulgacao_dia_publicacao":pa.Column(pa.String, nullable=True),
        "total_recomendacoes":pa.Column(pa.Int),
        "total_aeronaves_envolvidas":pa.Column(pa.Int),
        "ocorrencia_saida_pista":pa.Column(pa.String)
    }
)

In [57]:
df['ocorrencia_uf'].drop_duplicates()

0       PR
1       MG
2       GO
3       RJ
4       AM
5       SP
8       PA
9       AP
10      BA
11      MS
13      SC
19      PE
26      DF
29      RR
31      MT
33      RS
45      RO
66      MA
100     PB
103     RN
116     CE
119     ES
143     AL
147     AC
174    ***
329     PI
376     TO
692     SE
Name: ocorrencia_uf, dtype: object

In [58]:
df['ocorrencia_uf'].value_counts()

SP     1355
MG      534
PR      455
RJ      429
RS      336
MT      298
GO      281
PA      278
AM      227
BA      196
SC      186
MS      166
DF      116
PE      101
CE       80
ES       75
MA       67
RR       58
AC       52
RO       51
TO       46
PI       39
AL       29
PB       24
RN       19
SE       14
AP       13
***       4
Name: ocorrencia_uf, dtype: int64

In [59]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,80898,80898,80898,80898,80898,INCIDENTE GRAVE,-23.330278,-51.136667,LONDRINA,PR,...,2022-08-04,21:10:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
1,80895,80895,80895,80895,80895,INCIDENTE GRAVE,-16.70611111111,-43.82194444444,MONTES CLAROS,MG,...,2022-08-02,15:05:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2,80894,80894,80894,80894,80894,INCIDENTE,-15.438611,-51.598333,JUSSARA,GO,...,2022-07-31,13:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3,80887,80887,80887,80887,80887,INCIDENTE,-22.810000,-43.250556,RIO DE JANEIRO,RJ,...,2022-07-30,01:23:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,80886,80886,80886,80886,80886,INCIDENTE,-7.27888,-64.76944,LÁBREA,AM,...,2022-07-29,17:12:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5524,45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
5525,45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
5526,45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
5527,52243,52243,52243,52243,52243,INCIDENTE,NaN,NaN,UBATUBA,SP,...,2012-01-06,14:30:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5528,52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO

# Limpeza dos dados
Converter os dados marcados com "***", "###", etc, com alguma representação de dados não informados, como a sigla "DNI".

Quem pode dizer que tais dados podem assim serem classificados é o especialista no negócio.

In [60]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,80898,80898,80898,80898,80898,INCIDENTE GRAVE,-23.330278,-51.136667,LONDRINA,PR,...,2022-08-04,21:10:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
1,80895,80895,80895,80895,80895,INCIDENTE GRAVE,-16.70611111111,-43.82194444444,MONTES CLAROS,MG,...,2022-08-02,15:05:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2,80894,80894,80894,80894,80894,INCIDENTE,-15.438611,-51.598333,JUSSARA,GO,...,2022-07-31,13:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3,80887,80887,80887,80887,80887,INCIDENTE,-22.810000,-43.250556,RIO DE JANEIRO,RJ,...,2022-07-30,01:23:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,80886,80886,80886,80886,80886,INCIDENTE,-7.27888,-64.76944,LÁBREA,AM,...,2022-07-29,17:12:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [65]:
df.loc[1,"ocorrencia_cidade"]

'MONTES CLAROS'

In [69]:
df.loc[1:4,"ocorrencia_uf"]

1    MG
2    GO
3    RJ
4    AM
Name: ocorrencia_uf, dtype: object

In [76]:
df.loc[1]

codigo_ocorrencia                               80895
codigo_ocorrencia1                              80895
codigo_ocorrencia2                              80895
codigo_ocorrencia3                              80895
codigo_ocorrencia4                              80895
ocorrencia_classificacao              INCIDENTE GRAVE
ocorrencia_latitude                   -16.70611111111
ocorrencia_longitude                  -43.82194444444
ocorrencia_cidade                       MONTES CLAROS
ocorrencia_uf                                      MG
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             SBMK
ocorrencia_dia                    2022-08-02 00:00:00
ocorrencia_hora                              15:05:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero                       ***
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 1, dtype: object

In [77]:
df.loc[[10,30]]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
10,80885,80885,80885,80885,80885,ACIDENTE,"-14,92416","-41,95666",CONDEÚBA,BA,...,2022-07-27,13:40:00,SIM,ATIVA,A-086/CENIPA/2022,NÃO,NaN,0,1,SIM
30,80856,80856,80856,80856,80856,ACIDENTE,- 2.728333,- 60.812778,BOA VISTA,RR,...,2022-07-12,10:40:00,SIM,ATIVA,A-083/CENIPA/2022,NÃO,NaN,0,1,NÃO

In [78]:
df.loc[:,"ocorrencia_cidade"]

0             LONDRINA
1        MONTES CLAROS
2              JUSSARA
3       RIO DE JANEIRO
4               LÁBREA
             ...
5524            VIAMÃO
5525     SÃO SEBASTIÃO
5526          SÃO SEPÉ
5527           UBATUBA
5528      PORTO ALEGRE
Name: ocorrencia_cidade, Length: 5529, dtype: object

## Alteração do índice (label)

In [80]:
df.codigo_ocorrencia.is_unique

True

In [82]:
df.set_index('codigo_ocorrencia',inplace=True)

In [83]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
80898,80898,80898,80898,80898,INCIDENTE GRAVE,-23.330278,-51.136667,LONDRINA,PR,BRASIL,...,2022-08-04,21:10:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
80895,80895,80895,80895,80895,INCIDENTE GRAVE,-16.70611111111,-43.82194444444,MONTES CLAROS,MG,BRASIL,...,2022-08-02,15:05:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
80894,80894,80894,80894,80894,INCIDENTE,-15.438611,-51.598333,JUSSARA,GO,BRASIL,...,2022-07-31,13:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
80887,80887,80887,80887,80887,INCIDENTE,-22.810000,-43.250556,RIO DE JANEIRO,RJ,BRASIL,...,2022-07-30,01:23:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
80886,80886,80886,80886,80886,INCIDENTE,-7.27888,-64.76944,LÁBREA,AM,BRASIL,...,2022-07-29,17:12:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [85]:
df.loc[80898]

codigo_ocorrencia1                              80898
codigo_ocorrencia2                              80898
codigo_ocorrencia3                              80898
codigo_ocorrencia4                              80898
ocorrencia_classificacao              INCIDENTE GRAVE
ocorrencia_latitude                        -23.330278
ocorrencia_longitude                       -51.136667
ocorrencia_cidade                            LONDRINA
ocorrencia_uf                                      PR
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             SBLO
ocorrencia_dia                    2022-08-04 00:00:00
ocorrencia_hora                              21:10:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero                       ***
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            SIM
Name: 80898, dtype: object

In [86]:
df.reset_index(drop=True,inplace=True)

In [87]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,80898,80898,80898,80898,INCIDENTE GRAVE,-23.330278,-51.136667,LONDRINA,PR,BRASIL,...,2022-08-04,21:10:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
1,80895,80895,80895,80895,INCIDENTE GRAVE,-16.70611111111,-43.82194444444,MONTES CLAROS,MG,BRASIL,...,2022-08-02,15:05:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2,80894,80894,80894,80894,INCIDENTE,-15.438611,-51.598333,JUSSARA,GO,BRASIL,...,2022-07-31,13:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3,80887,80887,80887,80887,INCIDENTE,-22.810000,-43.250556,RIO DE JANEIRO,RJ,BRASIL,...,2022-07-30,01:23:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,80886,80886,80886,80886,INCIDENTE,-7.27888,-64.76944,LÁBREA,AM,BRASIL,...,2022-07-29,17:12:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO